[groups.anonymous.rules.games_read]
template = "collection('games').anyRead()"
[groups.anonymous.rules.user_read]
template = "collection('users').anyRead()"

# Should only be able to write to games in which you own
[groups.anonymous.rules.write_games]
template = "collection('games').anyWrite()"
validator = """
  (context, oldValue, newValue) => {
    return context.id === newValue.user_id && (!old || context.id === old.user_id);
  }
"""
#
# # Should only be able to write to your own gamer profile
[groups.anonymous.rules.write_users]
template = "collection('users').anyWrite()"
validator = """
  (context, oldValue, newValue) => {
    return context.id === newValue.id;
  }
"""
